#!/usr/bin/env sh

#
# Installs vedv on the system
#

set -eu

# ENV VARS
readonly DESTDIR="${DESTDIR:-}"

mkdir -p "${DESTDIR}/etc"
cp -vr dist/etc/vedv "${DESTDIR}/etc"

install -Dm644 dist/etc/skel/.vedv.env \
  "${DESTDIR}/etc/skel/.vedv.env"

mkdir -p "${DESTDIR}/usr/lib"
cp -vr dist/usr/lib/vedv "${DESTDIR}/usr/lib"

install -v -Dm755 dist/usr/bin/vedv \
  "${DESTDIR}/usr/bin/vedv"

install -v -Dm644 dist/usr/share/licenses/vedv/LICENSE \
  "${DESTDIR}/usr/share/licenses/vedv/LICENSE"

chmod -v 755 "${DESTDIR}/usr/lib/vedv/components/builder/__bin/vedvfile-parser"

# MANDATORY ENV VAR: DIR
export DIR="$(mktemp -d)"
./tools/gen-manpages

cp -v "${DIR}/"*.gz /usr/share/man/man1

echo ''
echo '>> INSTALLED SUCCESSFULLY'

cat <<'MSG'

>> CONFIGURE VEDV:

# copy the config to your home directory
cp /etc/skel/.vedv.env ~/

# edit the file and configure the registry
vim ~/.vedv.env
MSG
