#!/usr/bin/env sh

#
# Installs vedv on the system
#

set -eu

# ERRORS
readonly ERR_INVAL_ARG=69

# ENV VARS
readonly OS="${OS:-}"
readonly DESTDIR="${DESTDIR:-}"

# INSTALLS VEDV
if [ -n "$OS" ]; then

  readonly install_deps="tools/install-pkgs-prod-${OS}"

  if [ ! -f "$install_deps" ]; then
    echo "invalid os: ${OS}" >&2
    echo "file '${install_deps}' not found" >&2
    return "$ERR_INVAL_ARG"
  fi

  "$install_deps"
fi

cp -vr dist/etc/vedv "${DESTDIR}/etc"

install -m644 dist/etc/skel/.vedv.env \
  "${DESTDIR}/etc/skel/.vedv.env"

cp -vr dist/usr/lib/vedv "${DESTDIR}/usr/lib"

install -v -Dm755 dist/usr/bin/vedv \
  "${DESTDIR}/usr/bin/vedv"

install -v -Dm644 dist/usr/share/licenses/vedv/LICENSE \
  "${DESTDIR}/usr/share/licenses/vedv/LICENSE"

chmod -v 755 "${DESTDIR}/usr/lib/vedv/components/builder/__bin/vedvfile-parser"

echo ''
echo '>> INSTALLED SUCCESSFULLY'

cat <<'MSG'

>> CONFIGURE VEDV:

# copy the config to your home directory
cp /etc/skel/.vedv.env ~/

# edit the file and configure the registry
vim ~/.vedv.env
MSG
