#!/usr/bin/env bash
#
# Install manjaro dev packages
#

set -eu

. ./packages.env

sudo pacman -Syu --noconfirm --needed yay

yay -Sy --noconfirm --needed "${PACKAGES_DEV_MANJARO_YAY[@]}"

sudo -H npm install -g "${PACKAGES_DEV_ANY_NPM[@]}"

# Configure
git config core.hooksPath .githooks
