#!/usr/bin/env bash
#
# Install manjaro prod packages
#

set -eu

. ./packages.env

## Configure virtualbox 7.0 repo

wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc |
  sudo gpg --dearmor --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg

echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" |
  sudo tee /etc/apt/sources.list.d/virtualbox.list

sudo apt-get update -y
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y "${PKG_PROD_UBUNTU_APT[@]}"

sudo -H pip3 install "${PKG_PROD_UBUNTU_PIP[@]}"
