#!/usr/bin/env bash
#
# Install manjaro prod packages
#

set -eu

. ./packages.env

sudo pacman -Syu --noconfirm --needed yay

yay -Sy --noconfirm --needed "${PKG_PROD_MANJARO_YAY[@]}"

sudo -H pip3 install --break-system-packages "${PKG_PROD_MANJARO_PIP[@]}"
