#!/usr/bin/env bash
#
# Install manjaro prod packages
#

# shellcheck disable=SC2015

set -eu

. ./packages.env

sudo pacman -Syu --noconfirm --needed yay

yay -Sy --noconfirm --needed "${PKG_PROD_MANJARO_YAY[@]}"

command -v vboxreload >/dev/null && sudo vboxreload || :

sudo -H pip3 install --break-system-packages "${PKG_PROD_MANJARO_PIP[@]}"
