#!/usr/bin/env bash
#
# List manjaro dev dependencies
#

set -eu

. ./packages.env

echo '# YAY'
pacman --color never -Q "${PKG_DEV_MANJARO_YAY[@]}"

echo '# NPM'
npm list -g |
  grep -Po '\s\K.*' |
  grep -E "$(tr ' ' '|' <<<"${PKG_DEV_MANJARO_NPM[*]}")"
