#!/usr/bin/env bash
#
# List manjaro dev dependencies
#

set -eu

. ./packages.env

echo '# APT'
apt -qq list --installed bash python3 python3-pip virtualbox-7.0 "${PKG_PROD_UBUNTU_APT[@]}" 2>/dev/null |
  sed -E 's/\/\S+//' |
  awk '{print $1, $2}'

echo '# PIP'
pip list |
  grep -E "$(tr ' ' '|' <<<"${PKG_PROD_UBUNTU_PIP[*]}")" |
  tr -s ' '
