#!/usr/bin/env bash
#
# List manjaro prod dependencies
#

set -eu

. ./packages.env

echo "# SYSTEM: $(uname -a)"

echo '# YAY'
pacman --color never -Q bash python3 "${PKG_PROD_MANJARO_YAY[@]}"

echo '# PIP'
pip list |
  grep -E "$(tr ' ' '|' <<<"${PKG_PROD_MANJARO_PIP[*]}")" |
  tr -s ' '
